[project]
name = "snsimagedl-bot"
version = "1.0.0"
description = "A discord bot to automatically download all SNS embedded images"
requires-python = ">=3.14,<4.0"
dependencies = [
    "discord.py"
]
authors = [
    { name = "DizzyNight", email = "laffey@dizzynight.moe" }
]

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"
