[project]
name = "snsimagedl-lib"
version = "1.0.0"
description = "A library for downloading and tagging images (medias) from SNS sites"
requires-python = ">=3.14,<4.0"
dependencies = [
    "pyexiv2>=2.15.5",
]
authors = [
    { name = "DizzyNight", email = "laffey@dizzynight.moe" }
]

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"