[project]
name = "snsimagedl-pixiv"
version = "1.0.0"
description = "A snsimagedl pixiv extension for downloading from Pixiv"
requires-python = ">=3.14,<4.0"
dependencies = [
    "asyncio",
    "pixivpy3>=3.7.5",
    "msgspec"
]
authors = [
    { name = "DizzyNight", email = "laffey@dizzynight.moe" }
]

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"